### ISSUE TITLE
Ability to change y-axis of scatter plot to a different column

### ISSUE THREAD

**Issue by josenimo** [josenimo/napari-cell-gater#1]
Cylinter implements a scatter plot that just uses channel-to-be-gated intensity on the x-axis, and Area of segmentation mask on y-axis. 

Changing the y-axis to another marker in the quantification matrix can be beneficial. In cases where the markers are mutually exclusive (i.e. do not show co-expression), the orthogonality of the markers can provide better context than Area, and hopefully result in better gating decisions.

**Comment by melonora** [comment]
Hehe yeah this one I also had in mind.

**Comment by josenimo** [comment]
done with https://github.com/melonora/napari-cell-gater/pull/12
