### ISSUE TITLE
Scaling in large screen is weird

### ISSUE THREAD

**Issue by josenimo** [josenimo/napari-cell-gater#16]
As seen in attached imaged, widgets are very large.
Not sure how simple to match windows scale of things.

![IMG_20240416_111414](https://github.com/melonora/napari-cell-gater/assets/30318135/13c725ea-79d2-4c5d-baf0-da4b9b4a2b3f)

**Comment by melonora** [comment]
hmm can you try to slide it smaller? A little bit left to the pointer you should have the option to drag. First see if this works otherwise we have to adjust the size policies. This mostly got changed with your recent changes.

**Comment by josenimo** [comment]
I tried to drag it, and it did not work

**Comment by melonora** [comment]
ok, for now to get more space you can undock it, but have to look at the margins. QT is a bit challenging with multiple elements each having their own size policies.

**Comment by josenimo** [comment]
maybe a way to fix it?
https://stackoverflow.com/questions/71852282/qt-designer-not-playing-nicely-with-windows-display-scaling

**Comment by melonora** [comment]
I don't think so as it is not purely related to text size. Each widget has a size policy including the parent widget

**Comment by josenimo** [comment]
I think this is a napari issue, napari menues are also all unscaled, but only some parts of them.
I feel this will need some backend to fix.. Will carry on with a side monitor for scatter plot :) 

![IMG_20240417_100029](https://github.com/melonora/napari-cell-gater/assets/30318135/faa42790-33bc-40eb-8a64-3dcc74d0255d)
![IMG_20240417_100020](https://github.com/melonora/napari-cell-gater/assets/30318135/03b5e630-dec8-4a41-a333-a9a8b5fb5e4c)

**Comment by josenimo** [comment]
updated NVIDIA drivers and now it works
