### ISSUE TITLE
Automatic contrast limits?

### ISSUE THREAD

**Issue by josenimo** [josenimo/napari-cell-gater#8]
Images when loaded, Napari automatically shows only min/max, this can be a problem with artefacts.
Perhaps lets use an automatic contrast setter? 
90% quantile as max value should evade most artefacts, but could also kill very good signal to noise stains..
I would rather let the users deal with it

**Comment by melonora** [comment]
You can also calculate based on some crops in grid pattern in the image, avoiding most artefacts.

**Comment by josenimo** [comment]
I think that makes sense, but still can be problematic. Have seen images were positive signal is less than 1% of area. and if max is hard to change, this will lead to user friction. Rather leave the full range.. However, if good range is too small, say 400 to 1000, this is very inconvenient to drag in 16bit 0-65535, Typing explicit ranges also possible. So nonissue in the end.

**Comment by josenimo** [comment]
For current purposes, I think Napari contrast limits will do.
