### ISSUE TITLE
Clicking Validate adds more widgets and image/mask layers

### ISSUE THREAD

**Issue by josenimo** [josenimo/napari-cell-gater#9]
Validate button should check and delete previous sample selection widget and viewer layers.
And reload current, just in case.

**Comment by melonora** [comment]
I will probably deactivate and if a user selects another input clear the dockwidget until user has specified all input and validated again

**Comment by josenimo** [comment]
automatically hiding the select data widget into a tab, should prevent users from clicking validate more than once. Worst case, just restart napari.
